site_name: Strongman
site_url: https://strongman.standish.site
site_description: Project documentation
site_author: Lloyd Standish
site_dir: site
repo_url: https://github.com/lstandish/strongman/
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: false

nav:
    - Home: index.md
    - User Guide: user-guide.md
    - More:
        - Demo: more/demo.md
        - Release Notes: more/release-notes.md
        - Contributing: more/contributing.md
        - License: more/license.md
        - Development: more/development.md
        - Credits: more/credits.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - codehilite

# copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
# google_analytics: ['UA-27795084-5', 'mkdocs.org']
copyright: Copyright &copy; 2021 Lloyd Standish

plugins:
    - search
